version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE=chat-messages-local
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 